### ISSUE TITLE
v 2.x release date?

### ISSUE THREAD

**Issue by jasells** [rdavisau/sockets-for-pcl#102]
Is there any guess as to a v 2.x release date?  I've been watching this project eagerly awaiting the v 2 release.  I've used v 1.2 on a couple of project, but would really like some features of 2.0 for my new project.

If there is anything I can do to help look into issues blocking a v 2 release, let me know.  =)

**Comment by rdavisau** [comment]
Howdy @jasells, sorry about the long delay. 
[2.0.2](https://www.nuget.org/packages/rda.SocketsForPCL/2.0.2) is up on NuGet now - let me know if you have any issues!
