### ISSUE TITLE
Cannot initialized TcpSocketClient

### ISSUE THREAD

**Issue by ljrlt** [rdavisau/sockets-for-pcl#113]
Hello,

I am having an issue when doing this : `TcpSocketClient client = new TcpSocketClient();`. It throws a System.NotImplementedException with this message : "_System.NotImplementedException: The empty PCL implementation for Sockets was loaded. Ensure you have added the Sockets nuget package to each of your platform projects_."

Even after I install the nuget package on each platform, the issue is the same. I tried to debug and I found something interesting. When it is initializing, it opens a window to find this file "_C:\Users\rdavis\Source\Repos\sockets-for-pcl-for_real\Sockets\Sockets.Plugin\TcpSocketClient.cs_", but it was searching in a projet folder which is not related at all with my current project. I found the file in the Temp folder, but when I linked it, it still throws the same exception.

I am working on Windows 10 with Visual Studio 2015, my starting project is a Blank App (Xamarin.Forms Portable). I do not know if I did something wrong, I began Xamarin last week and I am still learning how to code. I apologize for my english, it is not my native language.

Thank you kindly.

**EDIT 1 :** I make another project with just this, it was not working too, until I updated Xamarin.Forms. Now I am doing this to my main project.

**EDIT 2 :** Everything work, I just needed to update Xamarin.Forms.

**Comment by rdavisau** [comment]
Glad to hear it worked out \😄/
