### ISSUE TITLE
TCPClient stay alive , send message and receive

### ISSUE THREAD

**Issue by SmartAv** [rdavisau/sockets-for-pcl#117]
Hello , i'm trying to do smart Home application which will connect to TCP Server 

i was using socket on Unity but i decided to move to xamarin 
i tried your plugin it's great , just when i connect to server and send message , i want to stay connected and send the message 

not after i disconnect the message be sent , because i need to keep the client connected to the server for the server sending update sometimes to the client 

how it can be done ?

**Comment by SmartAv** [comment]
ok i got it , it's my fault since i don't understand too much i forgot to use 
 StreamWriter _streamWriter;

then i do that afte rconnect 
_streamWriter = new StreamWriter(client.GetStream());

```
        _streamWriter.WriteLine("text");
        _streamWriter.Flush();
```

thank you , this answer for anybody had the same miss understanding like me

**Comment by rdavisau** [comment]
Yes - the socket was likely being flushed on disconnect - you could call `Flush` yourself (as you have done) or specify a `0` buffer size if you're happy with the implications of that 👍
