### ISSUE TITLE
UWP socket server not working

### ISSUE THREAD

**Issue by betoled** [rdavisau/sockets-for-pcl#119]
Hi,

I'm using sockets-for-pcl in a cross platform project, using Visual Studio 2015.
The NuGet package has been added to all projects in the solution.
When I run the Android project I can connect using a TCP socket client, but when I run the UWP project I cannot not connect and get a timeout.
There is not error message but I just cannot connect to the socket server.

This is my code in the Portable project

` public MainPage()
        {
            InitializeComponent();

            StartSocketServer();
        }

        private async void StartSocketServer()
        {
            int port = 11000;
            TcpSocketListener listener = new TcpSocketListener();
            
            listener.ConnectionReceived += Listener_ConnectionReceived;

            try
            {
                await listener.StartListeningAsync(port);
            }
            catch (Exception ex)
            {
                throw;
            }
        }`
Any idea why this is not working ?

Thanks,
Benjamien

**Comment by rdavisau** [comment]
Howdy,

First worth checking the listening side is fine - if not, I'd say the most likely cause is that `StartListeningAsync` is throwing an exception and if that's the case, the fact that your method is `async void` might be making it difficult to catch. It's probably worth reading up a bit about [why async void should be avoided](https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=async%20void) and factoring it out to a `Task` - In general, don't start async methods in a constructor. If it is throwing an exception, my guess is that you still need to [grant the appropriate permissions in the app manifest](https://github.com/rdavisau/sockets-for-pcl#platform-considerations) - UWP falls in the same basket as windows phone (I should update that given the way things have progressed in the last two years!). 

On the connecting side, it can be an issue of network connectivity and/or firewalls. Depending on the combination of client physical device vs emulator and listener physical device vs emulator, your connection may need to traverse networks or use a different IP address. If you describe more about the connectivity scenario (what devices are physical/emulator, what networks they are on etc.) I might be able to help more 🤔

**Comment by betoled** [comment]
Hi,

Thanks for your reply.

I refactored the code, but still no exception and still not able to connect.
The server is on my development computer, the client is on my laptop in the same network. Both have there firewalls disabled.
I am able to connect to another socket server I made (pure windows app) so my network setup is not the problem.

This is my new code 
``public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();

            StartServer();
        }

        private async void StartServer()
        {
            try
            {
                var server = new SocketServer();
                await server.StartSocketServer();
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
    public class SocketServer
    {
        public async Task StartSocketServer()
        {
            int port = 11000;
            TcpSocketListener listener = new TcpSocketListener();

            listener.ConnectionReceived += Listener_ConnectionReceived;
            
            await listener.StartListeningAsync(port);
        }

        private async void Listener_ConnectionReceived(object sender, Sockets.Plugin.Abstractions.TcpSocketListenerConnectEventArgs e)
        {
            
        }
    }
``

**Comment by betoled** [comment]
There seems to be a problem with my solution.
I created a completely new solution and copied the code, and now it works.

Thanks,
