### ISSUE TITLE
Need bound port number for TCPListener(port=0)

### ISSUE THREAD

**Issue by sdetweil** [rdavisau/sockets-for-pcl#120]
I have a protocol where I send a message via broadcast to any of my servers on my local network. in the message is the port address for the server to open a TCP Socket back (UDP back into a mobile device is a mess)...

SO, I need to set up a listen on the next available port, and then get that port number for inclusion in the message I send to wake up the server discovery thread.  

but TCPListener.LocalPort is null. 

also would like a way to get the local network broadcast address, instead of using all networks below
(altho I think my home router doesn't send those on. )

right now I have a routine that binds a socket gets its port, then releases the socket
and re-uses the port number..  there is a risk that some other task could steal that port from under me.

```// my code (I want to call startListenAsync with port=0
 TcpSocketListener listener = new TcpSocketListener(bufferSize); 
// setup the listen and callback handler
   // setup the listen and handler
                   await listenforServerResponse( 0, listener, bufferSize,  
                        (Object e, string data) =>
                        {
                            Log.Info("mirror debug", ">>> in callback with data="+data);

                            //Check if we actually got any data
                            if (data.Length > 0)
                            {
                                Log.Info("mirror debug", ">>> callback response from server:  '" + data + "'");
                                
                                // check if its the right respose
                                if (data.StartsWith(expectedResponse))
                                {                                   
                                    string port_info = data.Substring(expectedResponse.Length);
                                    TcpSocketClient client = (TcpSocketClient)e;
                                    serveraddress = client.RemoteAddress + ":" + port_info;
                                    Log.Info("mirror debug", ">>> callback real server address= '" + serveraddress + "'");
                                    // cancel any remaining wait
                                    tokenSource.Cancel();                                     
                                }
                            }
                            else
                            {
                                Log.Info("mirror debug", ">>> NO response from any server:");
                            }
                        }
                    );

                    Log.Info("mirror debug", "local ip address is " + ipAddress.ToString() + " port=" + listener.LocalPort);
                    // the send message, identifying us to the server
                    byte[] sendData = Encoding.UTF8.GetBytes(MirrorRequest+ listener.LocalPort);

                    // send, wait for it to finish
                    await socket.SendToAsync(sendData,sendData.Length,Netinfo.getBroadcastAddress(context).ToString(), ReceiverPort);


// called setup rotuine----------------------------------
 private async Task<int> listenforServerResponse(int port, TcpSocketListener listener, int bufsize, EventHandler<string> callback)
        {
            int rc = 0;
            try
            {
                var listenPort = port;

                // when we get connections, read byte-by-byte from the socket's read stream
                listener.ConnectionReceived += async (sender, args) =>
                {
                    var client = args.SocketClient;
                    Log.Info("mirror debug", "receiver fired");
                    var bytesRead = -1;
                    var buf = new byte[bufsize];

                    while (bytesRead != 0)
                    {
                        bytesRead = await args.SocketClient.ReadStream.ReadAsync(buf, 0,buf.Length);
                        if (bytesRead > 0)
                        {
                            var data = Encoding.UTF8.GetString(buf, 0, bytesRead);
                            Log.Info("mirror debug", "mirror response data='" + data+ "' from:"+client.RemoteAddress+":"+client.RemotePort);
                            callback(client, data);
                        }
                    }
                };

                // bind to the listen port across all interfaces
                await listener.StartListeningAsync(listenPort);
                Log.Info("mirror debug", "listening  on port " + listener.LocalPort);

            }
            catch (Exception ex)
            {
                Log.Info("mirror debug", "exception on listen="+ex.Message);
            }
            return rc;
        }

**Comment by rdavisau** [comment]
Howdy,

Can you format the code sample properly using triple backticks to make it easier to follow?
Hard to know what the cause could be but there are a few issues I can see with the code as-is that might be contributing -

- `listenForServerResponse` should be `async Task` not `async void` and should be `await`ed at the call site
- `StartListeningAsync` should be `await`ed, otherwise execution will proceed without waiting for the binding to complete. Also, any error during binding will not be captured without the `await` call (and the `async void` will mess that up too).

As `LocalPort` is an `int`, so it itself can't be null - if you are getting a NRE on that call to me that suggests that the platform socket is not set. For example, [on .NET platforms](https://github.com/rdavisau/sockets-for-pcl/blob/dev/Sockets/Sockets.Implementation.NET/TcpSocketListener.cs#L101-L104) the `_backingTcpSocketListener` or the `LocalEndPoint` might be null. Hard to say without sorting out the `async`/`await` parts - it may not be set because you are logging before `StartListeningAsync` completes, or it may be erroring and that's the issue - my first thought would be to make those changes and then let's see where we get to.

**Comment by rdavisau** [comment]
For the broadcast address, you can take a look at the `CommsInterface` abstraction - there's a bit about it in the readme [here](https://github.com/rdavisau/sockets-for-pcl/#binding-to-a-specific-interface). Depending on platform support, interfaces returned from `CommsInterface.GetAllInterfacesAsync()` will have the broadcast address in the `BroadcastAddress` property 👍

**Comment by sdetweil** [comment]
thanks for the tip on code formatting. done

**Comment by sdetweil** [comment]
sorry, close() to me was the comment, not the issue..

**Comment by sdetweil** [comment]
I have posted the updated code, using await, and it works perfectly on droid, and hangs on iOS. 
the listenforServerResponse() never returns, even tho it is marked async

there is a known issue on iOS with await getting confused.  the 'fix is to use await Task,Run().. but that doesn't work here

**Comment by sdetweil** [comment]
no matter what I try I get a hang on StartListenAsync() and StopListenAsync() on iOS. 

```
setup listen and callback
                    Task l = listenforServerResponse(port, listener, bufferSize,
                         (Object e, string data) =>
                         {
                             Log.Info("mirror debug", ">>> in callback with data=" + data);

                            //Check if we actually got any data
                            if (data.Length > 0)
                             {
                                 Log.Info("mirror debug", ">>> callback response from server:  '" + data + "'");

                                // check if its the right respose
                                if (data.StartsWith(expectedResponse))
                                 {
                                     string port_info = data.Substring(expectedResponse.Length);
                                     TcpSocketClient client = (TcpSocketClient)e;
                                     serveraddress = client.RemoteAddress + ":" + port_info;
                                     Log.Info("mirror debug", ">>> callback real server address= '" + serveraddress + "'");
                                    // cancel any remaining wait
                                    tokenSource.Cancel();
                                 }
                             }
                             else
                             {
                                 Log.Info("mirror debug", ">>> NO response from any server:");
                             }
                         }
                     );
                    // wait for the listen setup to complete
                    await l;    
#-----   listen.LocalPort is still bad here

                    Log.Info("mirror debug", "local ip address is " + ipAddress.ToString() + " port=" + listener.LocalPort);
                    // the send message, identifying us to the server
                    byte[] sendData = Encoding.UTF8.GetBytes(MirrorRequest+ port);

                    // send, wait for it to finish
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
                    Task s =socket.SendToAsync(sendData,sendData.Length,Netinfo.getBroadcastAddress(context).ToString(), ReceiverPort);

# wait for the listen to start, get the port info 
                    await s;

#------------------- the setup, no wait
        private async Task<Task> listenforServerResponse(int port, TcpSocketListener listener, int bufsize, EventHandler<string> callback)
        {
            var listenPort = port;
            Task t = null;
            try
            {
                // when we get connections, read byte-by-byte from the socket's read stream
                listener.ConnectionReceived += async (sender, args) =>
                {
                    var client = args.SocketClient;
                    Log.Info("mirror debug", "receiver fired");
                    var bytesRead = -1;
                    var buf = new byte[bufsize];

                    while (bytesRead != 0)
                    {
                        bytesRead = await args.SocketClient.ReadStream.ReadAsync(buf, 0, buf.Length);
                        if (bytesRead > 0)
                        {
                            var data = Encoding.UTF8.GetString(buf, 0, bytesRead);
                            Log.Info("mirror debug", "mirror response data='" + data + "' from:" + client.RemoteAddress + ":" + client.RemotePort);
                            callback(client, data);
                        }
                    }
                };

                // bind to the listen port across all interfaces
                Log.Info("mirror debug", "start listening  on port " + listenPort);
                t = listener.StartListeningAsync(listenPort);
                //Log.Info("mirror debug", "listening  on port " + listener.LocalPort);
               // don't wait here, let the caller wait
            }
            catch (Exception ex)
            {
                Log.Info("mirror debug", "exception on listen=" + ex.Message);
            }
            Log.Info("mirror debug", "listener setup complete  on port " + listenPort);
            return t;

**Comment by sdetweil** [comment]
On iOS I can't await in any of the places I think I should be able to await.. like sendAsync().. hangs if awaited

**Comment by rdavisau** [comment]
`async/await` works fine on iOS, but if you're not familiar with it (and even when you are) then it's easy enough to create a deadlock - depending on how you call the code in your example that may be the case here, hard to say. I'm having a bit of trouble understanding what you want to do here, this is my interpretation:

"app wants the server to connect to it, but wants to delegate the decision of which port to listen on to the OS, therefore needs to start listening first, then tell the server where it's listening." So, I think you want the below behaviour:

- app starts listening on dynamic port
- app tells server which port it's listening on
- app waits for a connection.

On that understanding I propose you refactor like this:

```
public async Task RequestConnection()
{
	var bufferSize = 1024;
	var listener = new TcpSocketListener(bufferSize);

	// set up what should happen when we get a connection
	var responseSource = new TaskCompletionSource<ITcpSocketClient>();
	listener.ConnectionReceived += (sender, e) => responseSource.TrySetResult(e.SocketClient);
	
	// start listening
	await listener.StartListeningAsync(0);
	
	// we're now bound, tell the server where we're at
	var localPort = listener.LocalPort;
	var sendData = Encoding.UTF8.GetBytes(... + localPort)
	await socket.SendToAsync(...);

	// wait till we get a connection from the server
	var serverSocket = await responseSource.Task; // set by the connection received handler above
	await listener.StopListeningAsync();
	
	// serverSocket represents the inbound connection
}
```

This is based on the assumption that you only want to deal with one connection (the first you receive after the broadcast). If you want to support multiple incoming connections, you would kick off `LongRunning` tasks from the `ConnectionReceived` event (these become threads, but that is a dirty word in this Brave New World) to run the processing of each of those - and you would not `await` those. If you wanted to do the message validation stuff (the code related to `expectedResponse` in the sample, I wasn't sure whether this was just for testing or a requirement) you could do that in the connection received handler and only call `TrySetResult` when the response is valid.

**Comment by sdetweil** [comment]
right, my mobile client is trying to discover the presence and configured port for interaction of my server.
so, as I don't know where it is on the network, I broadcast on a known port. ( on my local network, not for 5 routers away!)
if there IS a server, it will send back its configuration data at the port I specify on the broadcast.

1 message out (udp broadcast), 1 message back (tcp listen and receive).  both sides have to parse the message for the data to complete the process.   And of course, its possible that there IS NO server, so there has to be timeout recovery in here too. 

our code is fundamentally the same, except for the approach you use on  setting up the callback,
and waiting on it. (which is unknown to me)   this is my first mobile app, and I want it on multiple platforms. your stuff looks fantastic. 

I like to be a little verbose until I understand the details, then refactor where possible. I don't see where in your example I can put my code to handle the message contents..   

the await startlisten hangs EVERY time on iOS.. works pefectly on Android. 
there should be NO difference if I call it from a subroutine or on the current thread. 

and I separated  the receive message task into two parts..  listen, get raw data, and validate
and handle validated data (however it arrived, as I've had to play with the protocol a bunch, originally planned on bidi-UDP, but inbound UDP to mobile is a mess for developers).

anyhow.. I will look at what you are proposing. I am unhappy cause I want to push this stuff into the PCL
but I can't get the identical code working on 2 platforms like it should. 

as a long time system & app developer, doing lots of multi tasking and threading, this should NOT be this hard.

**Comment by rdavisau** [comment]
I get the frustration, I went through the same kind of thing when I first started using `async/await`. It really is worth spending some time reading up on it and how it works, because it can definitely simplify some scenarios. More importantly here though is that it's required for lots of mobile scenarios including use of this library - and doing it wrong or by halves can lead to lots of trouble and seemingly strange behaviour etc. In particular, the way you call into async code actually does matter, because if you aren't "async all the way", you are at risk of deadlocking or "missing" exceptions - and depending on the rest of your application either of those could appear to be 'hanging'. 

On the PCL comment - this code will all definitely work in a PCL - that's the core goal of the library. I didn't realise you had the code running in the platform projects, of course it is possible but keeping it in the PCL is the way to go. 

For adding the validation, you can change the connection received handler e.g. like this
```
listener.ConnectionReceived += (sender, e) => 
{
    // do the validation here .. read from the socket etc.
    
    if(!valid)
        return;  // bail early if we're not happy that this is one of our servers etc.

    responseSource.TrySetResult(e.SocketClient);
}

```

For timeouts, you can use a `CancellationToken` that fires after a given delay to give up on waiting. Here's an [example](https://gist.github.com/rdavisau/a3bfa15fc77fbc789c59) of an extension method that implements cancellation for any given `Task<T>`. Again, having a good understanding of `async/await` will be useful for using it. [This post](http://blog.stephencleary.com/2012/02/async-and-await.html) and more by the same guy are a pretty good place to start.

**Comment by sdetweil** [comment]
thanks.. I use the cancelation token for the timeout already.. 
have to add the CommsInterface.GetAllInterfacesAsync() stuff yet

can u change your example.. FirstUsable() really is more than likely localhost, which really isn't useful. 
is there  a way without hand written looping?

**Comment by sdetweil** [comment]
another tasking problem.. I just don't understand.. 
I want to use the CommsInterface. but it has async, so i MUST AWAIT.

but I get trash.. notice the 1st iteration thru the loop, the netmask value is not yet set
how can this be if await waited??

then this routine MUST be async cause of the need to await for the interfaces list. 
so I HAVE to await for it back in the calling routine. but the caller never wakes up from the await

(all on iOS)  works perfectly on Droid).
I added this to the routine above
                    string bca =await getbroadcastAddress();

2016-12-06 09:10:38.398 TestExpress.iOS[2563:2470941] mirror debug:loop interface addres=127.0.0.1 mask=
2016-12-06 09:10:38.400 TestExpress.iOS[2563:2470941] mirror debug:exception=Object reference not set to an instance of an object
2016-12-06 09:10:38.400 TestExpress.iOS[2563:2470941] mirror debug:loop interface addres=192.168.2.12 mask=192.168.2.255
2016-12-06 09:10:38.401 TestExpress.iOS[2563:2470941] mirror debug:interface addres=192.168.2.12 mask=192.168.2.255
2016-12-06 09:10:38.401 TestExpress.iOS[2563:2470941] mirror debug:returning interface addres=192.168.2.12 with mask=192.168.2.255

        private async Task<string> getbroadcastAddress()
        {
            string ia = null;
            var allInterfaces = await CommsInterface.GetAllInterfacesAsync();

            ICommsInterface firstUsable = null;

            foreach (var inter in allInterfaces)
            {
                try
                {
                    Log.Info("mirror debug", "loop interface addres=" + inter.IpAddress.ToString() + " mask=" + inter.BroadcastAddress);
                    if (inter.IsUsable && inter.IsLoopback == false && inter.IpAddress != localhost)
                    {
                        firstUsable = inter;
                        break;
                    }
                }
                catch(Exception ex)
                {
                    Log.Info("mirror debug", "exception=" + ex.Message);
                }
            }

            if (firstUsable != null)
            {
                ia = firstUsable.BroadcastAddress;
                Log.Info("mirror debug", "interface addres=" + firstUsable.IpAddress.ToString() + " mask=" + ia);
            }
            Log.Info("mirror debug", "returning interface addres=" + firstUsable.IpAddress.ToString() + " with mask=" + ia);
            return ia;
        }

-----
if I put this code inline instead of making it another async subroutine. the await never returns. 
I added the whole module.  really not complex.  and the one that works reliably on droid.

**Comment by sdetweil** [comment]
I ended up having to remove all 'await' requests and add taskinstance.Wait() 
now it runs the same on both Droid and iOS platforms.   I had to add one await call (never used) to support the caller using await..

this code is in the PCL project. 

[discovery.zip](https://github.com/rdavisau/sockets-for-pcl/files/637048/discovery.zip)

**Comment by rdavisau** [comment]
On the interfaces side that call worked fine, it's most likely that the OS doesn't return a netmask for loopback, which is the first item in the loop. 

Removing `await`s and blocking may 'work' in this instance as I have been diligent enough to avoid any context switches in the library code, but it's generally a risky assumption - [here's an explanation](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) of why. Regardless, if your code is not `await`ed and is called from the UI thread it will freeze everything, which is not gonna be fun with a 10 second timeout. For the UX, maintainability and because you're likely to hit it again with other libraries, I still think it's worth spending some time getting across async and friends.
