### ISSUE TITLE
TcpSocketClient and TcpCLientListener on same machine

### ISSUE THREAD

**Issue by jasells** [rdavisau/sockets-for-pcl#125]
This *should* be an easily accomplished example: create a client and a server in the same app/machine.  However, since TcpSocketClient.ConnectAsync(serverName, remotePortNum) automatically assigns localPort = remotePortNum, this causes an exception saying the port is already in use.

I was able to manually bind to an OS provided local port as so in a WPF test app (in this test case remoteAddr== localAddr):

```
var localEP = new System.Net.IPEndpoint(localAddr, 0);//let OS provide an available local port
TcpSocketClient.Socket.Client.Bind(localEP);
TcpSocketClient.ConnectAsync(remoteAddr, port);
```
And all was well with a server and client in one app on one machine.

This would be useful in PCL as well. 

The following link suggested an addition of an IPEndpoint abstraction, for other reasons, that may also work well here.  
[https://github.com/rdavisau/sockets-for-pcl/issues/114]()

However, the simplest approach would be just to add an additional param to `TcpSocketClient.ConnectAsync(string address, int port, int localPort = 0)`
 and allow OS defined local ports be default.  Or, set localPort = -1 default, and internally check:

`if(localPort < 0)
   localPort = port`

The latter option would probably be backwards compatible with current release(s) and not break any code that may be dependent on the assumption that localPort == RemotePort.

**Comment by rdavisau** [comment]
Howdy,

Are you sure you're seeing that issue? There should be no code in the .NET or UWP implementations that attempts to specify what the local port should be when connecting - both call into the native equivalent's `Connect`-style call with host and port. You can see in the LINQPad samples (e.g. the [strings](https://github.com/rdavisau/sockets-for-pcl/blob/dev/Sockets/linqpad-samples/Tcp/Strings.linq) one) that listening and connecting on the same machine is possible. Here I've modified the strings sample slightly to output the socket after the client has connected, and you can see the local endpoint's port is randomly assigned (in this instance we connected to remote 50000 and were bound to local 56514).

![image](https://cloud.githubusercontent.com/assets/7392704/23187316/1502ad2e-f8d6-11e6-9b9c-7726df363036.png)
 
Is there something I'm missing? I wonder what could be the cause 🤔

**Comment by jasells** [comment]
I am copying my email reply, since it didn't show up here...

Ok, well I was testing in WPF, not UWP.  Maybe this is specific to WPF?
 

Also, I wasn’t connecting to “localhost”.  I used the IP address assigned to the physical NIC.

 

JAS

**Comment by jasells** [comment]
I tried my test app again, and today, it is working as expected.  Strange.  Yesterday, I did have to change ports before it finally started working, so perhaps I had a dangling socket out there that didn't close correctly that was holding that port?
