### ISSUE TITLE
TcpSocketClient-UnhandledException when I try read a response that not arrived yet 

### ISSUE THREAD

**Issue by mayconddsilva** [rdavisau/sockets-for-pcl#128]
Hi, I'm using this library to communicate with a TCP Server, that sends me when a event was generated, then, I have to verify all the time if the TCP Server sent to me a event, but if I try read anything before the TCP Server sends me, it's thrown the UnhandledException, but it only happens if I read inside a Task, in the main thread it thrown a timeout exception, the exception that I expected to happen in Task. Someone can help me? Thanks. below is my code.

"04-11 13:32:24.490 E/mono    ( 4201): Unhandled Exception:
04-11 13:32:24.490 E/mono    ( 4201): System.NullReferenceException: Object reference not set to an instance of an object."

 I put a try/catch block to handle the exception, but it didn't work, someone can help me? Thanks.

`public class CentralTcpService
    {
        public async void ConnectTcpAsync()
        {
            try
            {
                _sockecClient = new TcpSocketClient();
                await _sockecClient.ConnectAsync(Central.Ip, Central.Port);
                _writter = new ExtendedBinaryWriter(_sockecClient.WriteStream);
                _reader = new ExtendedBinaryReader(_sockecClient.ReadStream);
                _writter.WriteString(EvenNotProtocol.MobileReceiverCommand);
                _sockecClient.ReadStream.ReadTimeout = int.MaxValue;

                EnableTcpService();
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        private void EnableTcpService()
        {
            _cancelationTcpService = new CancellationTokenSource();

             new Task(StartService, _cancelationTcpService.Token, TaskCreationOptions.LongRunning).Start();

        }

        private void StartService()
        {
            while (!_cancelationTcpService.Token.IsCancellationRequested)
            {
                var ev = EvenNotProtocol.DeserializeEvent(_reader);

                if (ev == null) continue;
                

                _writter.WriteString(EvenNotProtocol.MobileOkCommand);

                EventReceived?.Invoke(this, new CentralTcpEventArgs(ev));

            }
        }
    }
    
     public class EvenNotProtocol
     {
    
        public static Event DeserializeEvent(ExtendedBinaryReader reader)
        {
            try
            {
                reader.SkipBytes(1);
                .....
           }
           catch (IOException e)
           {
                return null;
           }
        }
     }`

**Comment by mddsilva** [comment]
I was testing more, and I realized that this only happens if I read inside a Task.

**Comment by rdavisau** [comment]
This is a late response but I suppose may be caused by the `async void` method, you can read here for an idea of why you should remove that https://haacked.com/archive/2014/11/11/async-void-methods/
