### ISSUE TITLE
The empty PCL implementation for Sockets was loaded.

### ISSUE THREAD

**Issue by tilo2804** [rdavisau/sockets-for-pcl#129]
Hi,
i installed the package rda.SocketsForPCL.2.0.2 with NuGet in my Project. If i run the following code i get the exception: 

_System.NotImplementedException: The empty PCL implementation for Sockets was loaded. Ensure you have added the Sockets nuget package to each of your platform projects.
04-14 18:30:09.442 I/MonoDroid( 3840):   at Sockets.Plugin.TcpSocketClient..ctor () [0x00006] in C:\Users\rdavis\Source\Repos\sockets-for-pcl-for_real\Sockets\Sockets.Plugin\TcpSocketClient.cs:22_

`var client = new Sockets.Plugin.TcpSocketClient();
await client.ConnectAsync(address, port);`

I develop a App with Xamarin Forms (v. 2.3.3.193) for Android 7.1 and iOS.

**Comment by mddsilva** [comment]
Hi, try install the package Sharpcaster.SocketsForPCL as well

**Comment by rdavisau** [comment]
You should install the NuGet into your PCL and all platform projects (iOS, Android, UWP etc.) also.
