### ISSUE TITLE
Can not using TcpSocketListener and TcpSocketClient on the same computer

### ISSUE THREAD

**Issue by tuanph** [rdavisau/sockets-for-pcl#148]
I ran example usage on the same computer, it take error:

> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 127.0.0.1:11000

It working if i run client and sever on 2 computer. I using XamarinForms, run with UWP project.
Thanks so much!

Sever:
```
var listenPort = 11000;
var listener = new TcpSocketListener();
    
// when we get connections, read byte-by-byte from the socket's read stream
listener.ConnectionReceived += async (sender, args) => 
{
    var client = args.SocketClient; 
    
	var bytesRead = -1;
	var buf = new byte[1];
		
	while (bytesRead != 0)
	{
		bytesRead = await args.SocketClient.ReadStream.ReadAsync(buf, 0, 1);
		if (bytesRead > 0)
            Debug.Write(buf[0]);
	}
};
    
// bind to the listen port across all interfaces
await listener.StartListeningAsync(listenPort);
```
Client:
```
var address = "127.0.0.1";
var port = 11000;
var r = new Random(); 
    
var client = new TcpSocketClient();
await client.ConnectAsync(address, port);
```

**Comment by rdavisau** [comment]
Hi there. I know that is generally possible to communicate via localhost using this library. However, for UWP specifically there is a restriction which I think you are probably hitting - https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app . If that's not the case, please reopen :)
