### ISSUE TITLE
Stream Buffering consistency between WinRT and .NET

### ISSUE THREAD

**Issue by xen2** [rdavisau/sockets-for-pcl#18]
Thanks for working on this project, really helpful!

When using same code to target both WinRT and .NET framework, I ran into some issues due to the fact that WinRT uses buffered socket (AsStreamForWrite() without int32 parameter means it uses a default quite huge 16k buffer) while .NET is not (NetworkStream).

Having this disparity is not so good because the way data is gathered in single TCP packet and FlushAsync() behavior are different (esp. bad on .NET since it will start a task with empty NetworkStream.Flush(), but we are forced to do it because WinRT is buffered).

I was thinking it would be better to make it more consistent by either:
- WriteStream is always buffered (i.e. wrap it around a BufferedStream in .NET)
- WriteStream is never buffered (use 0 as parameter).

So far I went with first approach (I could submit a PR) because making it not buffered on WinRT means that you can't do it afterwise (BufferedStream is not publicly exposed).

Another (probably better) option would be to add a parameter to specify buffer size on TcpSocketClient ctor (where 0 means not buffered).

**Comment by xen2** [comment]
I am currently implementing the better option described at the end (ctor parameter).

Just wondering, what would be the default behavior if nothing specified?
No buffering, or some specific value? (if yes, 1k? 2k? 16k?)

**Comment by rdavisau** [comment]
Hi, glad you are finding it useful! 

Agreed that a consistent buffering behaviour is better and I'm also a fan of the constructor approach. 
I'm tending towards no buffering as the default, primarily because it is the default for .NET and I expect more people are accustomed to that. 

Thanks for finding and working on it!
