### ISSUE TITLE
Windows Phone 8.0 Assembly version 

### ISSUE THREAD

**Issue by nfplay** [rdavisau/sockets-for-pcl#22]
Hi,

The Windows Phone 8.0 assembly version is still pointing at 1.1.7.0 instead of 1.2.0.0, causing all sort of "cannot find dll with version 1.2.0.0" errors.

Thanks,

**Comment by rdavisau** [comment]
Yikes, will pack the fix. Thanks for picking that up 👍

**Comment by rdavisau** [comment]
Ok, this is fixed in 1.2.1 - thanks again! :star2:
