### ISSUE TITLE
Expose DataAvailable property of NetWorkStream

### ISSUE THREAD

**Issue by jcalmonte** [rdavisau/sockets-for-pcl#24]
Im trying to use ReadByte to know when there is no more data available in a ReadStream, but for some reason I never get a -1 back, something like this:
``` 
while (bytesRec != -1)
{
    bytesRec = client.ReadStream.ReadByte();
}
```

 So i think it'll be nice to have the "DataAvailable" property exposed so that I we could do something like this instead:

``` 
while (client.ReadStream.DataAvailable)
{
    bytesRec = client.ReadStream.ReadByte();
}
```

**Comment by rdavisau** [comment]
Hi there, 

I'll look into this - I know we have `NetworkStream` and `DataAvailable` on .NET, but I'm not sure whether we can get the same kind of information on WinRT.

In the meantime, if it helps you could move to using `Read`/`ReadAsync` with a length of 1, and examine the return value to see how many bytes were received. It works like this:

- `> 0` - the number of bytes received and now in your output buffer
- `0` - no longer connected
- or it blocks and returns when there is some data to read.

So if you want to detect disconnection, you can test for 0. If you want to know that there's nothing sitting on the wire, you might try timing out the read call. Of course, if you haven't been disconnected yet, there's always the chance that more data will come after do your check, so you would probably want to check again later. Is there a reason you don't want to just loop on `ReadAsync` until you get data or a disconnect? That way you get your data as soon as it's available, don't need to worry about polling, etc.etc. It may be easier?

**Comment by rdavisau** [comment]
As above, it seems we can't get `DataAvailable`-style info from WinRT. To add to the previous suggestions, if you are concerned about waiting indefinitely when no data is available, it's possible to use a timed `CancellationToken` with `ReadAsync` to abort if no new data is seen for some period of time.
