### ISSUE TITLE
Define platform to install package

### ISSUE THREAD

**Issue by lcop200685** [rdavisau/sockets-for-pcl#28]
Hi 

I'm not sure if i'm doing a bad procedure or if there is a problem, i make a pcl library that it will work with android and IOS, and i installed the socket-for-pcl nuget package, according with the video of James Montemagno, and with your blog post about the bait and switch pattern, in the moment, i'm installing the nuget package, it should wonder me what platform target i'm like to install, but, when I install the package, it don't wonder me notihing, and when i execute the test, throw a exception because i have not defined the target platform

I'm using a xamarin library portable

I'm agree with your help

**Comment by rdavisau** [comment]
Hi @lcop200685,

If I understand correctly, you'd like to use sockets-for-pcl in a PCL targeting iOS and Android. If that's not the case, let me know. 

The selection of platform target actually occurs when you _create_ a new Portable Class Library, and looks something like this: 
![image](https://cloud.githubusercontent.com/assets/7392704/9125364/63da0b6e-3ce3-11e5-845b-bc09a7d48fd3.png)

If you have created your cross-platform solution using one of the Xamarin templates, it may have already chosen the appropriate targets for you. You can check or change the platforms that are targeted by right clicking your PCL in the solution explorer and checking the properties.

![image](https://cloud.githubusercontent.com/assets/7392704/9125396/bd8896f8-3ce3-11e5-83ad-515f684aba30.png)

When you install a package into your PCL using NuGet, it will check for you whether or not the chosen targets are compatible with the package. As you were able to install sockets-for-pcl into the PCL, your settings are compatible. 

The last step you need to do, to prevent exceptions at runtime, is install sockets-for-pcl into your iOS and Android projects too. One way to easily do this (having already installed it into your PCL) is to use the 'Manage NuGet packages for solution' menu option, filter on installed, and install it into the remaining projects.

![image](https://cloud.githubusercontent.com/assets/7392704/9125456/67dcdaba-3ce4-11e5-925b-92d99fd5ad2a.png)

With that you should be able to use sockets-for-pcl without problems. Let me know how you go :star2:

**Comment by lcop200685** [comment]
HI @rdavisau 

Thanks or your answer, the problem seems to be i hadn't added the pcl socket library in the unit test, the third point you explain has helped me, Thanks
