### ISSUE TITLE
SSL/ TLS Support 1.2

### ISSUE THREAD

**Issue by NVentimiglia** [rdavisau/sockets-for-pcl#35]
Hi, I am trying to connect to a secure server and getting exceptions.

First, here is my code.
`````
  public async Task ConnectAsync(string address, int port, CancellationToken cancellationToken)
        {
            try
            {
                //ortc-developers2-uswest2-s0001.realtime.co:443, true
                await _client.ConnectAsync(address, port, IsSecure);
            }
            catch (Exception se)
            {
                throw new WebException(string.Format("Failed to connect to '{0}:{1}'", address, port), se);
            }
        }
`````
Second, here is my exception

{System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.  at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert (AlertLevel alertLevel, AlertDescription alertDesc) [0x00013] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:574   at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x000d0] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:376   --- End of inner exception stack trace ---  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (IAsyncResult result) [0x00035] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:425   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x0000c] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:99   --- End of inner exception stack trace ---  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00026] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:104 --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124   at WebSocket.Portable.TcpConnection+<ConnectAsync>d__6.MoveNext () [0x00045] in E:\Projects\RT Debug\WebSocket.Portable\WebSocket.Portable\WebSocket.Portable\_Implementation\TcpConnection.cs:47 }

Lastly, I know mono has some issues with TLS 1.2
http://forums.xamarin.com/discussion/46332/http-client-connecting-to-server-with-tls-1-2

This can be solved by using the modernhttpclient
https://github.com/paulcbetts/ModernHttpClient

I will continue to look on me end. If you see that I am doing something wrong, let me know.

**Comment by NVentimiglia** [comment]
https://trello.com/c/PvUaV89u/16-tls-stack

**Comment by rdavisau** [comment]
Hey Nick,

Your code looks fine to me and I expect it is a limitation of the current Mono TLS implementation as you suggest. 

`ModernHttpClient` avoid any of these limitations as it wraps around native-based iOS and Android http libraries, bypassing the mono-based implementation completely. The equivalent here would be implementations for `TcpSocketClient` and friends that use the standard iOS framework socket (or a suitable third party wrapper) and the same for Android's java implementation. It would not be a trivial amount of work so I think it will be worth getting a better idea of what the status of the mono fixes are in the first instance. I'll do a bit of research.

**Comment by NVentimiglia** [comment]
Thanks for your help. In the meantime, I will take a closer look at the modern HTTP client.

**Comment by NVentimiglia** [comment]
Wanted to update on my progress.

1) I Experimented with WebSockets4Net. I was not able to get TLS working there either. I raised the issue with Kerry. https://github.com/kerryjiang/WebSocket4Net

2) I am now trying OKHttp.WS. This uses authobahn / supersocket internally. Again, TLS is not working. https://github.com/mattleibow/square-bindings/issues/4

3) I also tried to make a direct binding with the ibt.ortc android library. Binding projects use code generation to make a bridge library that can access the java classes from c#. The Binding project was not generating any ortc classes at all (but Simple-Json was working fine). Reading the docs this may be related to missing references, but,  I included android support and google gcm. There was no exceptions or helpfull output.

**Comment by NVentimiglia** [comment]
I have solved my issue using OkHttp / SuperSocket binding library.

**Comment by rdavisau** [comment]
Good to know you sorted it out. I see that the new RC that Xamarin put out ships with a version of mono that includes some of the ReferenceSource implementations from the Trello board you linked; with luck TLS will also come along eventually.
