### ISSUE TITLE
Possible to send whole objects instead of byte after byte?

### ISSUE THREAD

**Issue by janniksam** [rdavisau/sockets-for-pcl#37]
Hey,

I was wondering if it is possible to read more than just byte after byte?

Would like to send serialized objects over a TCP Connection and don't know how to do it yet.
I could read everý single byte and add the read bytes up a List<int>, when it's done reading try to convert it to a byte-array and then try to deserialize the byte-array... but I dont think this is the right way to do it.

So what would you suggest?

Thanks in advance

Jannik

**Comment by janniksam** [comment]
Well, I found your sockethelpers, they should help me and solve my question, but I have problems with the usage, please see:
https://github.com/rdavisau/sockethelpers-for-pcl/issues/2

**Comment by rdavisau** [comment]
Hi there - 

If you use [LINQPad](http://www.linqpad.net) by any chance, sockets-for-pcl comes with some samples, one of which demonstrates implementing a basic protocol for sending and receiving object instances. The relevant .linq file is [here](https://github.com/rdavisau/sockets-for-pcl/blob/master/Sockets/linqpad-samples/Tcp/Objects.linq) and demonstrates how to use a basic { length, payload } protocol for sending and receiving objects. 

As you have discovered, sockethelpers also has an implementation of this nature. I will review the issue you have referenced.
