### ISSUE TITLE
Connect to Remote Service and Timeout

### ISSUE THREAD

**Issue by Sparksteam** [rdavisau/sockets-for-pcl#46]
Hi - I'm a little lost in all this git stuff. I thought I forked your master, made some changes and committed into my fork. But it may have merged into your master. I did a clone from Git Shell, made the changes, added the repository from the GitHub app, and committed from there. I wanted to you to consider these changes via PR. At this point, I'm not sure where my changes went. If they went into your master, I apologize. 

I modified all 3 TcpSocketClient.cs files and the interface file

 to add support for a ConnectAsync() method to allow connection to remote service name, i.e. "http", and to override the default connection timeout.

Can you please check your repository? I'm attaching to 4 files here so you have another way to review my proposed changes. Whoops, looks like I'm unable to attach .cs files.

Please let me know how else I can get the files to you.

Thanks.

**Comment by rdavisau** [comment]
Will track this through the PR from now
