### ISSUE TITLE
UdpClient.SendToAsync no overload to specify #bytes from data to send

### ISSUE THREAD

**Issue by jasells** [rdavisau/sockets-for-pcl#50]
It is fairly obvious that the call will send the *entire* array.  That's fine, and simple, but what for the following case:
var udp = new UdpClient();
var stream = new MemoryStream();
... do some work, write varying len data to the stream...

//now, we have to *copy* from the existing buffer, to send....
stream.Position = 0;
var b = new byte[stream.Length - stream.Position];
ms.Read(b, 0, b.Length);udp.SendToAsync();

udp.SendToAsync(b, "127.0.0.1", 12345);

When we *could* have just done the following, with no extra copy.
var buff = stream.GetBuffer();
udp.SendToAsync(buff, stream.Length, "127.0.0.1", 12345);

Is this an unusual case, or is there something I'm missing?

**Comment by rdavisau** [comment]
Hi,

I see your point (and thank you for alerting me to the presence of `GetBuffer()` on `MemoryStream`!). 
I will add this in the next release :+1:

**Comment by jasells** [comment]
GetBuffer() is not available on MemoryStream in PCL’s… (only platform, and I’m not sure whoch ones beyond Windows Desktop and Android)  =(



Just FYI.  May be why you haven’t seen it.



I have created a IMemoryStreamExtension { byte[] GetBuffer() }


to work around that.








Sent from Surface





From: Ryan Davis
Sent: ‎Friday‎, ‎November‎ ‎20‎, ‎2015 ‎2‎:‎45‎ ‎AM
To: rdavisau/sockets-for-pcl
Cc: Joshua Sells





Hi,

I see your point (and thank you for alerting me to the presence of GetBuffer() on MemoryStream!). 
I will add this in the next release  :+1:

**Comment by rdavisau** [comment]
I've added this in 017698e13d03e2b65e8d88a099109a1a23561ff7. Will close this issue now for tracking purposes and come back to let you know when it's released!
