### ISSUE TITLE
Operation not supported

### ISSUE THREAD

**Issue by vbisbest** [rdavisau/sockets-for-pcl#54]
When I try to set the readtimeout property on WIndowsPhone, I get the following error:

socket.ReadStream.ReadTimeout = 5000;

Timeouts are not supported on this stream.

It works fine on Android.  Ideas?

**Comment by rdavisau** [comment]
Hi,

That's an annoying problem. Once you are accessing `ReadStream` you are dealing with the underlying .NET or WinRT class. However, we use the `AsStreamForRead` method on the `StreamSocket` to see it as a stream. In this case, it looks like `ReadTimeout` simply isn't supported on WinRT.

```csharp
var socket = new StreamSocket();
socket.InputStream.AsStreamForRead().ReadTimeout = 5000; // throws
```

I don't see anything elsewhere on the socket to set read timeout. In that case, I think it's best you roll your own over whatever `Read` method you use. You should be able to use [this](https://gist.github.com/rdavisau/a3bfa15fc77fbc789c59) extension method to get what you want, e.g.:

```csharp
socket.ReadStream.ReadAsync(...).TimeoutAfter(TimeSpan.FromSeconds(5));
``` 

Let me know how you go!

**Comment by rdavisau** [comment]
I assume this worked out OK - yell out if not. :+1:
