### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by risogolo** [rdavisau/sockets-for-pcl#56]
Is supposed also to work on UWP? I'm trying to use UdpSocketReceiver, but after receiver.StartListeningAsync(listenPort) call; 
receiver.MessageReceived never gets called.

**Comment by rdavisau** [comment]
Howdy, 

Only tested on Universal 8.1-style apps so far, but I don't forsee any reason that it wouldn't work on UWP. Can you share a small snippet of your code? 

Other things to check off the top of my head would be:
- appropriate manifest settings
- firewall settings if remote

**Comment by risogolo** [comment]
Basically I.m not doing anything else except what is described in your example for "A UDP receiver"
I have an old WPF application where I'm using built in .NET functionality for receiving UDP packets which works for me, but I need to rewrite it for UWP, As I wrote, my issue is that MessageReceived is never called. Firewall should not be an issue.

**Comment by rdavisau** [comment]
I was able to a UWP project up and running:

- in VS2015.1 using FIle -> New Project -> Blank Universal
- with Internet Client & Server enabled in the manifest
- with this mainpage xaml
```csharp
<Page
    x:Class="SocketsTest.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SocketsTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

        <StackPanel Background="White">
        <Button Content ="Listen" Name="listenButton" Background="Gray"/>
        <TextBlock Name="receivedMessagesTextBlock" VerticalAlignment="Stretch" Text=""/>
        <TextBox Name="messageToSendTextBox"></TextBox>
    </StackPanel>
</Page>
```

-with this code behind
```csharp
public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

            var dispatcher = CoreWindow.GetForCurrentThread().Dispatcher;
            var port = 40000;

            listenButton.Click += async (sender, args) =>
            {
                var listener = new UdpSocketReceiver();
                listener.MessageReceived += async (o, eventArgs) => await
                    dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
                    {
                        Debug.WriteLine(Encoding.UTF8.GetString(eventArgs.ByteData)); // works on any thread
                        receivedMessagesTextBlock.Text += Encoding.UTF8.GetString(eventArgs.ByteData) + Environment.NewLine; // has to be on UI thread
                    });

                await listener.StartListeningAsync(port);

                receivedMessagesTextBlock.Text += "Listening...\r\n";
            };
            
            var client = new UdpSocketClient();

            messageToSendTextBox.KeyUp += async (sender, args) =>
            {
                if (args.Key != VirtualKey.Enter || String.IsNullOrEmpty(messageToSendTextBox.Text))
                    return;

                await client.SendToAsync(Encoding.UTF8.GetBytes(messageToSendTextBox.Text), "localhost", port);
                messageToSendTextBox.Text = "";
            };

        }
    }
```
I can click the 'listen' button to start a `UdpSocketReceiver`, then type messages into the text box and press the enter key to have a `UdpSocketClient` send the message to that receiver. The message receiving loop runs off the main thread, so if you want to touch the UI you'll need to be back there -hence the dispatcher code. 

Can you get the above scenario (i.e. IPC) to work? If that works then we should consider more closely the rest of your setup. Let me know how you go :+1:

**Comment by risogolo** [comment]
This works, thx !, I need to play with that more, only difference I had is that I have similar code inside PCL library which I instantiate from an UWP page.

**Comment by rdavisau** [comment]
Good to hear! 

Yeah, I've typically used sockets-for-pcl in PCL-only or 'native-only' code, but there shouldn't be an issue with mixing and matching. I'll close this now but if you have any questions, yell out
