### ISSUE TITLE
Reading a byte array

### ISSUE THREAD

**Issue by freever** [rdavisau/sockets-for-pcl#6]
Hi,

Thanks for this plugin, I hope it's going to help alleviate some of the pain of my cross-platform sockets app. I'm a bit of a noob, and probably shouldn't even be playing with sockets at all, but anyway, here's my question. I can convert a string to a byte array and send it without any problems using this code:

public async Task SendData(string messageString)
        {
            var encoding = new System.Text.UTF8Encoding();
            var messageByteArray = encoding.GetBytes(messageString);
            foreach (var messageByte in messageByteArray)
            {
                _socketClient.WriteStream.WriteByte(messageByte);
                await _socketClient.WriteStream.FlushAsync();
            }
        }

The problem I have is reading the bytes at the other end and converting back to a string. ReadByte() seems to return an int, which I need to cast to a byte. But then to convert to string using Encoding.UTF8.GetString() I need an array of bytes. I don't know an easy way to keep adding bytes to an existing array, so I've used a List and then used ToArrayed to get it back into an array. The end result is I can read the first character of the string but then no more. This is probably a noob mistake, but I'm kinda lost, so I'd really appreciate a pointer. 

var resultLList = new List<byte>();
            var resultString = "";
            server.ConnectionReceived += ((sender, args) =>
            {
                resultLList.Add((byte)(args.SocketClient.ReadStream.ReadByte()));
                var resultArray = resultLList.ToArray();
                resultString += Encoding.UTF8.GetString(resultArray);
            });

Thanks!

**Comment by freever** [comment]
Ha ha - struggle for a day, post a help request, then immediately figure out a solution. This feels hcky, but it works:


server.ConnectionReceived += ((sender, args) =>
            {
                var nextChar = "";
                while (nextChar != "}")
                {
                    var charByte = new byte[1];
                    charByte[0] = (byte) args.SocketClient.ReadStream.ReadByte();
                    nextChar = Encoding.UTF8.GetString(charByte);
                    resultString += nextChar;
                }
            });

**Comment by rdavisau** [comment]
Howdy,

I see you have posted a solution, which is along the right lines. I'll give you some feedback on the original question as it may still be useful :)

On the send side, you don't need to send byte-by-byte, a stream has the method WriteAsync() which lets you send an array of bytes at once, and has the benefit of being `await`able. So once you have `messageByteArray` you can call `await _socketClient.WriteStream.WriteAsync(messageByteArray, 0, messageByteArray.Length)`, and flush, and all is good. 

On the receive side, you can also receive many bytes at once, but you need to keep in mind that unless you are adhering to a strict protocol with fixed message sizes, you need to find a way to tell when you have hit the end of a message. If you are passing strings back and forth, a common and easy method is to use a delimiter, which is what you have done in your solution - you read byte by byte and when you hit the `}` character, you end the message. You could also use the delimiter's byte representation to identify the end of the message without decoding it byte by byte, and then decode the entire result all at once.

An alternative delimiter approach is to create a buffer of a fixed size, use the `ReadAsync()` method to read multiple bytes at once, and then split the bytes on the delimiter to get messages. The `ReadMessage` method in the example on [this page](https://msdn.microsoft.com/en-us/library/system.net.security.sslstream(v=vs.110).aspx) is an example of that pattern, but looking at th at I worry about some edge cases that could creep in. 

A final alternative that I like is to implement a basic protocol that involves sending the length of the message before you send the contents. In this way you always know how many bytes you need to receive. For example:

On sending side:
````
var msg = "hi there";
var msgBytes = Encoding.UTF8.GetBytes(msg);
var msgLength = msgBytes.Length;
var msgLengthBytes = BitConverter.GetBytes(msgLength);

var allBytes = msgLengthBytes.Concat(msgBytes).ToArray(); // combine size and message into one for convenience.

await client.WriteStream.WriteAsync(allBytes, 0, allBytes.Length);
await client.WriteStream.FlushAsync();

````

On receiving side: 
````
var intSize = sizeof(int);

var lengthBytes = new byte[intSize];
await _client.ReadStream.ReadAsync(lengthBytes, 0, intSize); // read the size into lengthBytes
var length = BitConverter.ToInt32(lengthBytes); // convert bytes back into int representing length of msg

var msgBytes = new byte[length];
await _client.ReadStream.ReadAsync(msgBytes, 0, length); // read msg into msgBytes, we know length already
var msg = Encoding.UTF8.GetString(msgBytes, 0, msgBytes.Length);

// msg is "hi there"!
````

**Comment by freever** [comment]
Thank you, that's brilliant! You solved another problem I knew I was going to have at some point. Works like a charm!

**Comment by freever** [comment]
One more question if you don't mind. I can't figure out how to read responses in my TcpSocketClient. Using a listener there is the ConnectionReceived event you can handle, but I can't see any equivalent events in the TcpSocketClient. Do I need to create both a client and a listener in my mobile app - or is there a way to capture and handle data written to the socket using TcpSocketClient?

**Comment by rdavisau** [comment]
Sure. I'm not 100% sure I know quite what you're asking, but hopefully the below gives you what you need. If not, just ask.

- You use `TcpSocketListener` to bind to a port and wait for clients to connect. No communication goes through it, it just raises `ConnectionReceived` events when a client connects
- You use a `TcpSocketClient` to connect to an existing `TcpSocketListener` (or any external socket anywhere).
- A `TcpSocketClient` when connected, represents the connection between it and some remote socket; you write data to that remote socket via the `WriteStream` and you read any data back via the `ReadStream`. So, if you are using a `TcpSocketClient` to connect to something else, after calling `await client.ConnectAsync()`, you can write and read via those streams. 
- Finally, when a client connects to a `TcpSocketListener`, the `args.SocketClient` property in the `ConnectionReceived` event is a `TcpSocketClient` instance that represents the socket connection *from the listening side's perspective* - so writing to its `WriteStream` goes to the client that connected, and reading from its `ReadStream` will yield anything the client sent.

**Comment by freever** [comment]
Thanks for the info. It is helpful but I think my question was none too clear. 

I am writing a mobile app using Xamarin that talks to a node server using your PCL sockets package. Almost all the pieces are in place: I can connect from the app to the server and send the info I need to my node server using TCPSocketClient , and my server can process the info and respond by writing messages of its own back to the same socket. I also have client side code to parse and process those messages. 

What I can't figure out is how to actually access the incoming stream of data from the node server. I know I can call ReadAsync on the stream, but it's just not clear how and when to call the ReadAsync method. So I'm happily writing info to the stream, and sitting waiting for responses to pop off so I can process them, but I can't see how to join the final dots and actually bring those bytes off the stream into my processing pipeline. Do you know of any sample code out there that does this sort of thing with your library?

It's probably a very simple and obvious thing I am missing. 

Thanks again for all your help.

**Comment by rdavisau** [comment]
OK, I think I have a better idea of what you mean. If I understand correctly, you want to be able to write to the socket at will and get information back from it to process whenever there is something to process. Incidentally, I am working on a "sockethelpers" project which handles high level patterns like this for you, but it's not quite there yet. 

If the above is what you're after, one approach would be to run a "reader" continuously on a seperate thread/task, and notify or callback in some way when a message is received. My preferred method for doing that is via [Reactive Extensions](https://rx.codeplex.com/), but initially you could raise events or use callbacks.

So, a basic example:

````
// inside ConnectionReceived, start a loop reading from the socket off the main thread
Task.Factory.StartNew(async (obj) => {
 while(true) 
 {
    // do your work to read a message out here
     await socket.ReadStream.ReadAsync(....);
  
    // call a method or raise an event with your message data    
 }
}, TaskCreationOptions.LongRunning);

```

`ReadStream` blocks (waits) until there is data to read, and simultaneous reads and writes are thread safe, so this should help. Let me know how it goes.

**Comment by freever** [comment]
That's exactly what I needed, thanks!
