### ISSUE TITLE
I am having an issue with getting a list of platform interfaces.

### ISSUE THREAD

**Issue by doubledunk** [rdavisau/sockets-for-pcl#66]
I setup a PCL test project in visual studio 2015 and obtained the sockets plugin via NuGet (version 1.2.2)

My PCL is targetting the following platforms.
.Net 4.5
ASP.NET Core 5.0
Windows 8
Xamarin.Android
Xamarin.iOS
Xamarin.iOS (Classic)

When I make the following call I get the exception listed below.
List<CommsInterface> x = await CommsInterface.GetAllInterfacesAsync();

An exception of type 'System.NotImplementedException' occurred in Sockets.Plugin.dll but was not handled in user code

Additional information: The empty PCL implementation for Sockets was loaded. Ensure you have added the Sockets nuget package to each of your platform projects.

My question. Since I am running the code on a Windows 7 machine, shouldn't the implementation found in Sockets.Implementation.Net run instead of getting a NotImplemented Exception?

Thank you kindly,

**Comment by rdavisau** [comment]
Hi - if you mean a test project as in a project to run tests via xunit or something like that, you might need to do some trickery to have it load the correct .dll - [here](http://kent-boogaart.com/blog/using-the-visual-studio-test-runner-for-mobile-development/) is a post describing a possible work around. Another is to create a proper .NET project and add the tests from your PCL to it as linked files. 

If you mean a test project as in an experiment, then I guess you have two projects already - the PCL and the .NET project. If you get the above error it means you probably installed sockets-for-pcl into the PCL, but not the .NET project. If you install it into both, you should be fine. 

Let me know how you go!

**Comment by doubledunk** [comment]
Thank you very much for the prompt response good sir. My experiment project now works because of your recommendation and I shall now move into making a unit test project. 

Once again, thank you very much for all your help.

**Comment by rdavisau** [comment]
No problems! Glad I could help :+1:

**Comment by 0skill** [comment]
Hi. I'm trying to use Socket-for-PCL. So I've added it into my PCL and I get 'System.NotImplementedException' when try 'SendToAsync'. I read this posts and tried to add package into my UWP. But I got 'Payload contains two or more files with the same destination path '
