### ISSUE TITLE
Receive data with UdpSocketClient

### ISSUE THREAD

**Issue by mj1856** [rdavisau/sockets-for-pcl#7]
I am trying to implement an NTP client using your library.  I have to connect over udp port 123 to a remote server, send a data packet, and receive a reply packet.

[Here is the regular non-pcl version, which works fine.](http://stackoverflow.com/a/12150289).

I've rewritten the socket parts of that code with your library, as follows:

```csharp
using (var client = new UdpSocketClient())
{
    var tcs = new TaskCompletionSource<byte[]>();
    client.MessageReceived += (sender, args) =>
    {
        tcs.SetResult(args.ByteData);
    };

    await client.ConnectAsync(server, 123);
    await client.SendAsync(ntpData);
                
    ntpData = await tcs.Task;
}
```

A few things:

- It would be nice if you had a `SendAndReceiveAsync` method (or at least a `ReceiveAsync` method), so I didn't have to use a `TaskCompletionSource`.
- It works just fine when I test in a Windows Store application.  When I test in a regular .NET 4.5 application, it never receives any data.  Looking at the .NET implementation, it seems that `UdpSocketBase.RunMessageReceiver` is not called when using `UdpSocketClient`.  It's only called for `UdpSocketMulticastClient` and `UdpSocketReciever`.   So how can I receive response data in a unicast client scenario?

**Comment by rdavisau** [comment]
Hi! I'm away from my machine but here are a few thoughts for now:

Regarding your specific problem, using sockets-for-pcl for NTP was discussed recently [here](http://forums.xamarin.com/discussion/comment/115088#Comment_115088) and someone created a full XF sample [here](https://github.com/MitchMilam/NTPClient). I see there are some issues with interfaces going up/down that I'll need to look at but the general approach there is sound. The main change looks to be using UdpSocketReceiver, 

Regarding your first question, the WinRT implementation of UDP sockets does not expose streams, just a message received event, I guess it makes sense given the protocol but I agree it does make this sort of scenario a little awkward. 

Regarding the second question, you should always use UdpSocketReceiver if you intend to receive any data; UdpSocketClient only supports fire and forget sending.

**Comment by mj1856** [comment]
Thanks.  Looking at [their implementation](https://github.com/MitchMilam/NTPClient/blob/master/Demo-NTP/Demo_NTP/NTPClient.cs), it's a bit nonintuitive that you would need to open a listening port, but I guess the overhead would be relatively low.

Though determining if a port was already taken for something else might be a problem.

**Comment by rdavisau** [comment]
I was a little surprised to see that `UdpClient` in .NET was automaticallly binding in some cases. Again, in WinRT it looks like you can't get that behaviour and have to call bind yourself. 

Agreed that in cases like this it does not make sense for the developer to choose the bound port - I've pushed a new version to [NuGet](https://www.nuget.org/packages/rda.SocketsForPCL) that makes the `port` parameter optional in `StartListeningAsync`. If you don't set a port (or pass 0), the os will choose which port gets bound.

**Comment by rdavisau** [comment]
I will be including a UDP socket class that supports blocking receive in the next major version bump. It could be a few weeks away. There might also be a rationalisation of the existing UDP classes. In case you want the behaviour urgently, [this gist](https://gist.github.com/rdavisau/72052d6d86d983035130) shows how you can wrap `UdpReceiver` to get it. I'm expecting that the class that ends up in the the library will be API-compatible with the above gist. In any case, I'll let you know here when it's released.

**Comment by mj1856** [comment]
Thanks!
