### ISSUE TITLE
Strange problem on client side when receiving data continuously 

### ISSUE THREAD

**Issue by kellelein** [rdavisau/sockets-for-pcl#71]
I have a Xamarin.Forms app that communicate with a server over TCP/IP. I can send and receive messages and everything works like a charm.

Serverside I start a thread that sendt data continuously to the client. Everything seems to work, but after 50-200 packages the client side breakes down. (Client side I have a TcpSocketListener implemented)

My packages is 250 bytes on the server side and also 250 bytes on the client. When the problem occurs, the package on the client is suddently 720'ish bytes??? 

I have checked the packages sendt from the server, and they are always the same size... I don't understand why the packages received on the client suddently get that big.

I can see that ReadAsync has HasFaulted and Exception, but I can't figure out to read this???

I am very new to this TCP/IP ;-)

**Comment by rdavisau** [comment]
Howdy,

Sounds strange! Will need a few more details to diagnose -

* Is there any exception, or are you just seeing 'weird' package sizes from then onwards?
* can you share the code related to the 'client side'? Seeing the listen code and the reading code may give some clues.

**Comment by kellelein** [comment]
This is the Client side

`
private async void StartTCPListener()
        {
            try
            {
                TcpSocketListener listener = new TcpSocketListener();

                // when we get connections, read byte-by-byte from the socket's read stream
                listener.ConnectionReceived += OnReceived;

                // bind to the listen port across all interfaces
                await listener.StartListeningAsync(Common.Constants.Tcp.PORT + 22);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Exception in BrakeForceViewModelTest::StartTCPListener - Message: {0}", ex.Message);
            }
        }


        private async void OnReceived(object sender, TcpSocketListenerConnectEventArgs args)
        {
            try
            {
                Status = "Data received";
                
                ITcpSocketClient client = args.SocketClient;

                while (true)
                {
                    byte[] receiveBuffer = new byte[Common.Constants.Tcp.BUFFER_SIZE];
                    BrakeForceModelTest dataReceived = new BrakeForceModelTest();

                    int dataReceivedLength = await client.ReadStream.ReadAsync(receiveBuffer, 0, receiveBuffer.Length);

                    dataReceived = await SerializerHelper.DeSerializeJsonAndConvertToObject<BrakeForceModelTest>(receiveBuffer.Take(dataReceivedLength).ToArray());
                    await UpdateView(dataReceived);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Exception in BrakeForceViewModelTest::OnReceived - Message: {0}", ex.Message);
            }
        }
`

And this is the Server side

`
private static void StartSendingDataContinuously()
        {
            Task.Factory.StartNew(async () =>
            {
                try
                {
                    Console.WriteLine("Start sending data continuously.");

                    string androidPhoneIp = "10.0.50.156";

                    TcpClient client = new TcpClient(androidPhoneIp, Common.Constants.Tcp.PORT + 22);
                    Stream stream = client.GetStream();

                    int dataCounter = 1;

                    while (true)
                    {
                        BrakeForceModelTest data = new BrakeForceModelTest
                        {
                            Value = "Data from server",

                            BrakeForceLeft = "101",
                            //TimeStampLeft = DateTime.Now.ToString("hh:mm:ss"),
                            PackageNrLeft = dataCounter.ToString(),

                            BrakeForceRight = "102",
                            //TimeStampRight = DateTime.Now.ToString("hh:mm:ss"),
                            PackageNrRight = dataCounter.ToString(),
                        };

                        dataCounter++;
                        
                        byte[] dataToSend = await SerializerHelper.SerializeObjectJsonAndConvertToBytes(data);

                        Console.WriteLine("Datapackage nr. {0} sendt, size {1}", dataCounter - 1, dataToSend.Length);
                        
                        await stream.WriteAsync(dataToSend, 0, dataToSend.Length);
                        await stream.FlushAsync();

                        await Task.Delay(TimeSpan.FromMilliseconds(100));
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception in AsynchronousSocketListener::StartSendingDataContinuously - Message: {0}", ex.Message);
                }
            });
        }
`

**Comment by rdavisau** [comment]
Ok, I think you should recreate the issue and examine the larger payload you are receiving; that should help you determine what is happening!

TCP is stream-based, not message ('datagram') based; so besides the co-incidence of timing, there is no real link between a TCP socket's repeated calls to `WriteAsync` and what you get from a read on the other end. This is part of the reason that you need to specify a buffer when reading. It is possible (maybe for network/transient reasons), that after some time, two or more messages have been sent to the client between it calling `ReadAsync`. If the buffer size of your `ReadAsync` call is large enough, if will be populated with all the data already received. So if normally the message is 3 bytes 'msg', and your buffer is 10 bytes; and messages are sent 1 second apart, you might see something like this: 

`[ m s g - - - - - ]`

... 1 second ... 

`[ m s g - - - - - ]`

... 1 second ... 

`[ m s g - - - - - ]`

...

but if the server has sent two messages before you read, you could receive in one call:

`[ m s g m s g - - ]`

or three messages:

`[ m s g m s g m s ]`

^ here there is still more data in the system buffer from the third message that you need to call `ReceiveAsync` again for.

So, I think it's possible that for some reason the messages from the server queue up - maybe a few are delayed and then arrive at approximately the same moment (TCP guarantees order of messages, so if a server sends 6 messages, and messages `1`, `2`, `3`, `5` `6`, are acknowledged by the device (and `4` is not), you will only see `1`, `2`, and `3` immediately. Then after a moment then the sender will realise that it needs to re-send `4`, and then suddenly you will see `4`, `5`, `6`). When messages are queued up (in the internal system buffer), your call to `ReadAsync` will read them all at once (up to the buffer size). So, I think that if you examine the 'large message' you are receiving (convert the bytes to string), you might see that it is actually multiple of your json messages. 

If this is the case, the solution to this is to mark the boundaries of your messages somehow. The easiest solution in my opinion is to implement a basic protocol that prefixes each message with its length. [Here](https://github.com/rdavisau/sockets-for-pcl/blob/v1.2.2/Sockets/linqpad-samples/Tcp/Objects.linq#L62-#L115) is an example of doing it with json encoding (similar to what you are doing now, but with the serialisation and sending/receiving combined).

If this is not the case, let me know what data is contained in the 'large message' and maybe it will give some clues!

**Comment by kellelein** [comment]
Thank you very much for your help, I will look into it and get back to you :-)

**Comment by kellelein** [comment]
The problem lies exactly as described above. Thank you so much for pointing me in the right direction

**Comment by kellelein** [comment]
Problem solved :-)

**Comment by rdavisau** [comment]
Glad you were able to work it out!
