### ISSUE TITLE
Unix Header

### ISSUE THREAD

**Issue by GustavoTancredo** [rdavisau/sockets-for-pcl#72]
I would like to know how can I use write WriteStream.WriteAsync and inform the Header type "Unix Header'

**Comment by rdavisau** [comment]
Hi - apologies for the delay.
Can you be more specific regarding your use case? With a TCP socket you are writing and reading raw bytes, so I think the concept of headers should be protocol dependent.

**Comment by GustavoTancredo** [comment]
Hi .. tnks for your contact ...in my case the socket server read the first four bytes to know the size of buffer(message) so then it read the buffer using this parameter.

for example if the message buffer size is 680 bytes
|HEADER|BUFFER
|0680|message buffer

**Comment by rdavisau** [comment]
You should be able to simply encode the length of your message in bytes, and send before the message. In the below example the message is a string, so we convert to utf8 bytes first:

```cs
var socket = ...

// convert message to bytes
var message = "message";
var messageBytes = Encoding.UTF8.GetBytes(message);

// get length, convert that to bytes
var len = messageBytes.Length;
var lenBytes = BitConverter.GetBytes(len)

// combine length prefix with message
var allBytes = Enumerable.Concat(lenBytes, messageBytes).ToArray();

// send!
await socket.WriteStream.WriteAsync(allBytes, 0, allBytes.Length);		
```

In a tight loop, you might prefer not to combine the message but rather make two calls to `WriteAsync`; ensure you use `ConfigureAwait(false)` in this case. 

Hope that helps - let me know how you go!

**Comment by GustavoTancredo** [comment]
Tnks a lot your help.... my problem was fixed

**Comment by GustavoTancredo** [comment]
Hi... i'm here again.. one more time....

Sorry for disrupt you, this is not a bug or issue... its just a doubt

Now I can send the open the socket connection with the server.
And send the message using WriteStream.WriteAsync, this step is working perfectly

I saw the socket server Log, and the server after receve the message,it processed this request and sent the response.

But in my app How can I get this server response, after send for him the message  


regards Gustavo Tancredo

**Comment by rdavisau** [comment]
No problems - you can use `ReadStream.ReadAsync` for that!

If the response is in the same format (length before message) you should read an int's worth of bytes (`sizeof(int)`), convert that to int to know the message length, then read again from the socket until you have received that many bytes.

**Comment by GustavoTancredo** [comment]
Tnks a lot work nice
