### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by Yothri** [rdavisau/sockets-for-pcl#84]
Hi, i get this message.
I am using the Duality 2D Engine, added the NuGet Repository and installed the sockets-for-pcl package with that.

Now when i try to instantiate the TcpClient, it throws me a message:
http://puu.sh/oMIDw/9cfa110e68.png

Please help

**Comment by rdavisau** [comment]
Hi

I'm not familiar with the Duality engine, but the error you are seeing tells you that you need to make sure you have installed the NuGet package in both your PCL and any platform projects. So if you have a windows desktop, iOS, or Android or other project, it must also be installed there. How you do this in Duality depends on how it handles your projects. Do you use Visual Studio, or some engine specific IDE?

**Comment by Yothri** [comment]
Using Visual Studio. Well i didnt try more on this but i found another way to use Sockets now. Thanks anyways.
