### ISSUE TITLE
QUESTION: How to determine byte array size on the receiving end ?

### ISSUE THREAD

**Issue by MrFancyPhants** [rdavisau/sockets-for-pcl#87]
Before asking, I would like to thank the developers of this library, for basically saving my life with TCP connection. I'm developing a cross platform system, although I found my self in doubt. 

On the server side I'm creating a byte array which is dynamic, meaning that with more data the byte array increases, how should the client side know what size is the received byte array, since it needs to store the information in it's own byte array?

**Comment by Emixam23** [comment]
Hi !

I don't know if you're still stuck, but if I understand well your question (Maybe not..), it would be helpfull to take a look  at the Getline() function in C/C++ :)

I did code this function during my first year of studying in C but I don't know where I put the code.. However you have the doc for the C++ implementation on [C++ Reference](http://www.cplusplus.com/reference/string/string/getline/).

Answer if you found a solution before this message or if you have any question :)

**Comment by rdavisau** [comment]
Hi there,

Glad the library has helped! I will put 'life saving' on my resume 😄 

To handle a situation where you don't know the size of the data to be sent until it is being sent, you should implement a protocol in your send/receive code that can handle this. The two most common methods are:

**Sending a delimiter between messages:**

[f] [i] [r] [s] [t] [ ] [m] [e] [s] [s] [a] [g] [e] **[;]** [s] [e] [c] [o] [n] [d] [ ] [m] [e] [s] [s] [a] [g] [e] 

In the above, the receiver reads continuously and knows when one message has ended when it sees the *;* delimiter. This requires picking a delimiter that is not going to be in your message, and is a little unwieldy in my opinion, so I prefer the next approach.

**Prefixing each message with the length:**

**[13]** [f] [i] [r] [s] [t] [ ] [m] [e] [s] [s] [a] [g] [e] **[14]** [s] [e] [c] [o] [n] [d] [ ] [m] [e] [s] [s] [a] [g] [e] 

In the above, the receiver alternates between reading an integer to learn the message size, then reading that number of bytes to receive the message. This is my preferred approach, and you can see an example of the code for it [here](https://github.com/rdavisau/sockets-for-pcl/blob/v2.0.0-pre/Sockets/linqpad-samples/Tcp/Strings.linq#L56-#L101).

I think this should be enough to help you out, but let me know if you need any more guidance!

(@Emixam23 - Hi 👋 - I think the solution to #88 is similar, but will review your issue in detail the near future)

**Comment by Emixam23** [comment]
Ok thank ! :)

I just need something to exchange data with my TCP server (Go).
However my writing part seems to have a problem with WriteAsync() and I don't know how to handle input from the socket with something such as an event function ;)

**Comment by MrFancyPhants** [comment]
Perfect ! Thank you !

**Comment by rdavisau** [comment]
Glad it's working for you :smile:
