### ISSUE TITLE
UdpSocketClient throws exception when send subnet broadcast

### ISSUE THREAD

**Issue by EugenePeng** [rdavisau/sockets-for-pcl#89]
When using
client.SendToAsync(msgBytes, address, port);
to send a udp packet, if the address is a subnet address, an exception is thrown.
ie. send to address 192.168.0.23 it works fine.
But using address 192.168.0.255, will cause an exception.

**Comment by rdavisau** [comment]
Howdy - can you let me know:

- What platform and version?
- What version of sockets-for-pcl?
- Device or emulator/simulator?
- Exception and stacktrace

That will help to understand the problem.

**Comment by EugenePeng** [comment]
Sorry, my mistake, the problem is caused by my code in the receiving side. Android phone gives me an unhandled exception, the exception could not be caught which let me to believe the sending code was the problem.

**Comment by rdavisau** [comment]
No problems :+1:
