### ISSUE TITLE
Not working for UWP

### ISSUE THREAD

**Issue by vbisbest** [rdavisau/sockets-for-pcl#91]
I am getting an error when running a Xamarin Forms UWP project:

{"Could not load file or assembly 'Sockets.Plugin, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Sockets.Plugin, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null"}

Droid works fine.
Thanks.

**Comment by rdavisau** [comment]
From the error it looks like this is in the new 2.0.1. It's probably a packing error - I can take a look tomorrow and republish 💯

**Comment by vbisbest** [comment]
Great!  Looking forward to the new package.

**Comment by vbisbest** [comment]
And yes, this is 2.0.1-pre

**Comment by vbisbest** [comment]
Look like the same issue exists for Windows Phone.   Is the update coming soon?  Thanks!

**Comment by vbisbest** [comment]
And I have confirmed that in the packages directory, you have a mix of 2.0.1.0 and 2.0.0.0 in several of the platform folders.

**Comment by rdavisau** [comment]
Ok - it's all ready to go but I want to make sure it's totally correct before publishing and I won't have time till tonight. In the meantime you can download the pkg from [here](http://ryandavis.io/content/images/rda.socketsforpcl.2.0.2.nupkg/) if that helps. Sorry about the bad pack!

**Comment by joshwl2003** [comment]
Any update on this issue? I am using 2.0.1-pre and still have this issue.

**Comment by rdavisau** [comment]
@joshwl2003 2.0.2 stable is up on nuget now!
